### PR TITLE
Kodi 19 compatible version

### PR DESCRIPTION
**Pull request by guindous**
Provides a Kodi 19 compatible version of the plugin. This version, because the modifications, break compatibility with Kodi 18. 

Disclaimers:
- I'm not a python expert and was a Q&D direct migration. Expect rough edges: poor language use, non test scenario, etc. Said that, I've been using it for some days with success.
- I'm hosting this version on [my custom repo](https://github.com/guindous/repository.guindous) for an easier end-user install. If this PR is considered/merged, I will remove it.

### CODE REVIEW

**Comment by estemendoza** [comment]
Hey! Thanks for help. I think your PR looks fine, but I haven't got the change to try it, I have been away of this project for a few years.

Can you check if PR #9 is something that you might need to consider on this PR as well? About changing http to https, maybe we can marge them on a single PR

**Comment by guindous** [comment]
I'll analyze and merge other PRs on my spare time.

**Comment by guindous** [comment]
> Can you check if PR #9 is something that you might need to consider on this PR as well? About changing http to https, maybe we can marge them on a single PR

Done! Also removed unnecessary Kodi six dependency, because this changes not meant to be Kodi 18 compatible. 

Having said that, I've versioning this PR in a non standard way (_fourth point number notation_) due I didn't want to decide next version number just by myself. IMHO as this versions breaks compatibility with previous Kodi version, this should at least change minor version to 0.10.0. That way main users knows that 0.10 version and upwards are not compatible with Leia. Just my 2 cents.

**Comment by estemendoza** [comment]
Thanks for the help, give me a few days to give it a try and will merge if everything works fine

**Comment by martinrevert** [comment]
@estemendoza Por si te sirve, estuve probando el branch de @guindous en Kodi 19 y va perfecto. Saludos.

**Comment by guindous** [comment]
@martinrevert podrían confirmar la versión? para validar que tenga los últimos cambios... muchas gracias!

**Comment by martinrevert** [comment]
Hola @guindous Me arme el zip de tu branch "migrateToKodi19", en Kodi 19 me indica la versión 0.9.5.2, en teoría tengo lo último del changelog. Dado que no había desinstalado la vieja versión incompatible, al addon se actualizó OK. Gracias por la buena onda de actualizar este coso.

**Comment by estemendoza** [comment]
Gracias por la buena onda muchachos, si @martinrevert ya lo probo en Kodi 19, entonces mergeamos

**Pull request merged**
